### ISSUE TITLE
eliminate vulnerability issues

### ISSUE THREAD

**Issue by jtrs** [cubbles/cubx-grunt-wct-scaffolder#2]
* [x] cubx-wct-scaffolder#3.1.1 or cubx-wct-scaffolder#1.9.1
* [x] grunt#1.0.3
* [x] grunt-contrib-clean#1.1.0
* [x] load-grunt-configs#1.0.0
* [x] load-grunt-tasks#4.0.0
